#ifndef QT_JSON_SOCKET_LIB_GLOBAL_H
#define QT_JSON_SOCKET_LIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QT_JSON_SOCKET_LIB_LIBRARY)
#  define QT_JSON_SOCKET_LIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QT_JSON_SOCKET_LIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QT_JSON_SOCKET_LIB_GLOBAL_H
